name: toastr_flutter
description: A highly customizable Flutter package for displaying beautiful toast notifications with smooth animations, multiple types, and flexible positioning. Works like SnackBar with no initialization required.
version: 1.0.0+7
homepage: https://github.com/IgnacioMan1998/toastr
repository: https://github.com/IgnacioMan1998/toastr
issue_tracker: https://github.com/IgnacioMan1998/toastr/issues
documentation: https://github.com/IgnacioMan1998/toastr#readme

topics:
  - toast
  - notification
  - snackbar
  - alert
  - ui

screenshots:
  - description: 'Desktop configuration panel with all customization options'
    path: screenshots/desktop01.png
  - description: 'Desktop toast notifications in action'
    path: screenshots/desktop02.png
  - description: 'Mobile-responsive interface and configuration'
    path: screenshots/phone01.png

environment:
  sdk: ^3.9.0
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  # No assets required for this package
